spring.application.name=nsia-commons

# Server Config
server.port=8080
server.servlet.contextPath=/${spring.application.name}

# Spring Misc. Config
# To Disable Warning on Start-Up
spring.jpa.open-in-view=false

# Logging Level Config
logging.level.root=INFO
logging.level.com.nsia=DEBUG

# Custom JDBC Logging Config - Disable this on production
decorator.datasource.enabled=false
decorator.datasource.p6spy.log-format=%(currentTime)|%(executionTime)|%(category)|connection%(connectionId)|%(sqlSingleLine)

# Liquibase Config
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/master.changelog.yaml
#spring.liquibase.label-filter=sit

# Datasource Config
spring.datasource.url=jdbc:postgresql://localhost:55432/postgres?ApplicationName=${spring.application.name}
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Datasource Config - HikariCP
spring.datasource.hikari.pool-name=${spring.application.name}
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.connection-init-sql=SELECT 1
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000

# Redis Config
spring.data.redis.database=0
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=45000
spring.data.redis.repositories.enabled=false

# Distributed-Lock Config
distributed-lock.enable=true
distributed-lock.redis-lock-type=pub_sub_lock
distributed-lock.registry-key=${spring.application.name}:
distributed-lock.release-time-duration=180s
distributed-lock.create-va-waiting-time-duration=120s

# RestTemplateFactory Config - defaultRestTemplate
rest-template-factory.map-of-rest-template-config.default.suitable-hosts=*, localhost, .*svc
rest-template-factory.map-of-rest-template-config.default.connect-timeout=200ms
rest-template-factory.map-of-rest-template-config.default.socket-timeout=300ms
rest-template-factory.map-of-rest-template-config.default.logging-interceptor-config.enable=true
rest-template-factory.map-of-rest-template-config.default.logging-interceptor-config.default-level=INFO

# RestTemplateFactory Config - proxyEnabledRestTemplate
rest-template-factory.map-of-rest-template-config.proxyEnabled.suitable-hosts=.*nsia.com
rest-template-factory.map-of-rest-template-config.proxyEnabled.connect-timeout=200ms
rest-template-factory.map-of-rest-template-config.proxyEnabled.socket-timeout=600ms
rest-template-factory.map-of-rest-template-config.proxyEnabled.logging-interceptor-config.enable=true
rest-template-factory.map-of-rest-template-config.proxyEnabled.logging-interceptor-config.default-level=INFO
rest-template-factory.map-of-rest-template-config.proxyEnabled.proxy-config.enable=false
rest-template-factory.map-of-rest-template-config.proxyEnabled.proxy-config.host=proxy-http.proxy-${CONTAINER_ENV}.svc
rest-template-factory.map-of-rest-template-config.proxyEnabled.proxy-config.port=8443
rest-template-factory.map-of-rest-template-config.proxyEnabled.proxy-config.user=vanessa

# RestClientFactory Config - defaultRestClient
rest-client-factory.map-of-rest-client-config.default.suitable-hosts=*
rest-client-factory.map-of-rest-client-config.default.connect-timeout=200ms
rest-client-factory.map-of-rest-client-config.default.socket-timeout=300ms
rest-client-factory.map-of-rest-client-config.default.logging-interceptor-config.enable=true
rest-client-factory.map-of-rest-client-config.default.logging-interceptor-config.default-level=INFO

# RestClientFactory Config - proxyEnabledRestClient
rest-client-factory.map-of-rest-client-config.proxyEnabled.suitable-hosts=.*nsia.com
rest-client-factory.map-of-rest-client-config.proxyEnabled.connect-timeout=200ms
rest-client-factory.map-of-rest-client-config.proxyEnabled.socket-timeout=600ms
rest-client-factory.map-of-rest-client-config.proxyEnabled.logging-interceptor-config.enable=true
rest-client-factory.map-of-rest-client-config.proxyEnabled.logging-interceptor-config.default-level=INFO
rest-client-factory.map-of-rest-client-config.proxyEnabled.proxy-config.enable=false
rest-client-factory.map-of-rest-client-config.proxyEnabled.proxy-config.host=proxy-http.proxy-${CONTAINER_ENV}.svc
rest-client-factory.map-of-rest-client-config.proxyEnabled.proxy-config.port=8443
rest-client-factory.map-of-rest-client-config.proxyEnabled.proxy-config.user=vanessa
rest-client-factory.map-of-rest-client-config.proxyEnabled.proxy-config.password=vanessa12!@

# Kafka Producer Config
spring.kafka.producer.client-id=${spring.application.name}
#spring.kafka.producer.bootstrap-servers=alikafka-pre-public-intl-sg-l0z46ae6j09-1-vpc.alikafka.aliyuncs.com:9092,alikafka-pre-public-intl-sg-l0z46ae6j09-2-vpc.alikafka.aliyuncs.com:9092,alikafka-pre-public-intl-sg-l0z46ae6j09-3-vpc.alikafka.aliyuncs.com:9092
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.compression-type=gzip
spring.kafka.producer.properties.enable.idempotence=false
spring.kafka.producer.properties.max.block.ms=5000
spring.kafka.producer.properties.transaction.timeout.ms=5000

# App Config
app.embedded-postgres.enabled=true
